version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: "daniel"
      POSTGRES_PASSWORD: "Daniel1234567!"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"